language: julia
julia:
  - 0.4
  - 0.5

script:
  - julia -e 'Pkg.add("Coverage")'
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("PowerModelsLANL", coverage=true)'

after_success:
  - echo $TRAVIS_JULIA_VERSION
  - julia -e 'using Coverage; cd(Pkg.dir("PowerModelsLANL")); Codecov.submit(process_folder("."), codecov_url="https://cov.lanlytics.com", token="e69e281d-cd23-4aef-aeb5-40ed8bad2b49");'