language: julia
julia:
  - 0.4
  - 0.5


before_install:
  # IPOPT dependencies
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran
  - sudo apt-get install -y liblapack-dev
  - sudo apt-get install -y libglpk-dev
  # GLPK dependencies
  - sudo apt-get install -y libgmp-dev
  - julia -e 'Pkg.add("Coverage")'
  # Current tests requires the latest version of Pajarito
  - julia -e 'Pkg.add("Pajarito")'
  - julia -e 'Pkg.checkout("Pajarito")'

script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("PowerModelsLANL", coverage=true)'

after_success:
  - echo $TRAVIS_JULIA_VERSION
  - julia -e 'using Coverage; cd(Pkg.dir("PowerModelsLANL")); Codecov.submit(process_folder("."), codecov_url="https://cov.lanlytics.com", token="e69e281d-cd23-4aef-aeb5-40ed8bad2b49");'